# Startup — translated from Hyprland Startup_Apps.conf
exec swww-daemon --format xrgb
exec $scriptsDir/Polkit.sh
exec nm-applet --indicator
exec swaync
exec waybar
exec wl-paste --type text --watch cliphist store
exec wl-paste --type image --watch cliphist store
exec $scriptsDir/Nightlight.sh init
exec swayidle -w \
  timeout 540 'notify-send -i $HOME/.config/swaync/images/ja.png " You are idle!"' \
  timeout 600 '$HOME/.config/sway/scripts/LockScreen.sh' \
  before-sleep 'loginctl lock-session'
