# Startup — translated from Hyprland Startup_Apps.conf
exec swww-daemon --format xrgb
exec $scriptsDir/Polkit.sh
exec nm-applet --indicator
exec swaync
exec waybar
exec wl-paste --type text --watch cliphist store
exec wl-paste --type image --watch cliphist store
exec $scriptsDir/Nightlight.sh init
exec $scriptsDir/StartIdle.sh
